services:
  - type: web
    name: my-shop
    env: python
    buildCommand: ""
    startCommand: gunicorn my_shop.wsgi:application
    preDeployCommand: |
      python manage.py migrate
      python manage.py loaddata fixtures/goods/categories.json
      python manage.py loaddata fixtures/goods/products.json
      python manage.py loaddata fixtures/users/Users.json
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: my-shop.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: myshop-db
          property: connectionString

# Exported from Render on 2025-07-26T08:27:12Z
databases:
- name: My_db
  databaseName: my_db_utem
  user: my_db_utem_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
