services:
  - type: web
    name: my-shop
    env: python
    buildCommand: ""
    startCommand: gunicorn my_shop.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: myshop-db
          property: connectionString

databases:
  - name: myshop-db
    databaseName: shop
    user: shop_admin