# Generated by Django 4.2.21 on 2025-06-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='catigory',
        ),
    ]
